--- #YAML:1.0
name:               WWW-YourFileHost
version:            0.07
abstract:           Get video informations from YourFileHost
author:
    - Yusuke Wada <yusuke@kamawada.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CGI:             0
    LWP::UserAgent:  0
    Test::More:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
